target-version = "py310"  # Pin Ruff to Python 3.10
output-format = "full"

[lint]
preview = true
select = [
    "B",   # flake8-bugbear
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "W",   # pycodestyle
]
ignore = [
#    "E124",
#    "E125",
#    "E128",
    "E261",
#    "E301",
#    "E302",
#    "E303",
]
