version: 2.1

orbs:
  orb: invocations/orb@1.3.0


jobs:

  compat:
    parameters:
      python:
        type: string
        # baseline default, because why not
        default: "3.6"
      sphinx:
        type: string
        # New-enough that most other deps in ecosystem won't get pissy
        default: "4.5.0"
    executor:
      name: orb/default
      version: "<< parameters.python >>"
    steps:
      - orb/setup
      # Nuke ourselves and sphinx, for some cleanliness. (Ideal: a way to
      # install dev deps + some other tweak, in the same step; can pip do
      # that?)
      - run: "pip uninstall -y alabaster sphinx"
      # Get Sphinx under test, and then reinstall ourselves
      - run: "pip install -U sphinx==<< parameters.sphinx >>"
      - run: "pip install ."
      - run: "pip list --format=columns"
      # Make sure we can run (building our own docs, as we dogfood) w/o
      # exploding.
      # TODO: some suite of canaries to check for in the rendered html? How are
      # other themes/plugins testing themselves?
      - run: "inv docs"
      - orb/debug


workflows:
  main:
    jobs:
      # These will all happen under Python 3.6 by default
      - orb/lint:
          name: Lint
      - orb/format:
          name: Style check
      - orb/test-release:
          name: Release test
      - orb/docs:
          name: Docs
          task: "docs --nitpick"
      # We have no tests to matrix, and this is too niche for the orb, so just
      # do a bunch of install/run tests on different Python and Sphinx versions
      # for compat testing.
      # Split it up into two broad dimensions to avoid a huge product!
      - compat:
          name: "Docs (Py3.6/Sphinx << matrix.sphinx >>)"
          requires: ["Docs"]
          matrix:
            parameters:
              # TODO: still need to find a way to solve escaping hell on circle
              # re: parameters containing >< symbols
              sphinx:
                - "1.6.7"
                - "1.7.9"
                - "1.8.6"
                - "2.4.5"
                - "3.5.4"
                - "4.5.0"
                - "5.3.0"
                # 6.x already covered by the base docs job
      - compat:
          name: "Docs (Py<< matrix.python >>/Sphinx 1.6.7)"
          requires: ["Docs"]
          matrix:
            parameters:
              python:
                # 3.6 already covered by the base docs job
                - "3.7"
                - "3.8"
                - "3.9"
                - "3.10"
                - "3.11"
