name: Render docs

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3
        cache: pip
        cache-dependency-path: docs/requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r docs/requirements.txt

    - name: Render the documentation
      run: >
        sphinx-build
        -M html ./docs ./build
        --jobs=auto
        -T
        -W
        --keep-going
