name: Lint source code

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3

    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        python -m pip install "ruff==0.5.2"

    - name: Lint with Ruff
      run: |
        ruff check . --output-format github
        ruff format . --check
