name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  vary-sphinx:
    runs-on: ubuntu-latest
    name: Sphinx ${{ matrix.sphinx-version }}
    strategy:
      fail-fast: false
      matrix:
        sphinx-version:
        - "6.2"
        - "7.4"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3

    - name: Install Sphinx
      run: |
        python -m pip install -U pip
        python -m pip install "sphinx~=${{ matrix.sphinx-version }}.0"
        python -m pip install .

    - name: Run Sphinx
      run: >
        sphinx-build
        -M html ./docs ./build
        -j=auto
        -T
        -W
        --keep-going

  vary-python:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.10"
        - "3.11"
        - "3.12"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Sphinx
      run: |
        python -m pip install -U pip
        python -m pip install -U sphinx
        python -m pip install .

    - name: Run Sphinx
      run: >
        sphinx-build
        -M html ./docs ./build
        --jobs=auto
        -T
        -W
        --keep-going

  oldest-supported:
    runs-on: ubuntu-latest
    name: Oldest supported

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3

    - name: Install Sphinx
      run: |
        python -m pip install -U pip
        python -m pip install "sphinx~=6.2.0"
        python -m pip install .

    - name: Run Sphinx
      run: >
        sphinx-build
        -M html ./docs ./build
        -j=auto
        -T
        -W
        --keep-going
